apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.image }}
  storage:
    size: {{ .Values.cluster.storage.size }}
  postgresql:
    parameters:
      {{- range $key, $value := .Values.cluster.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  managed:
    roles:
      {{- range .Values.roles }}
      - name: {{ .name }}
        ensure: present
        comment: {{ default "" .comment | quote }}
        login: true
        superuser: false
        passwordSecret:
          name: {{ printf "%s-db-secret" .name | replace "_" "-"  }}
      {{- end }}
