{{- range .Values.roles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" .name | replace "_" "-"  }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .name }}
  password: {{ .password }}
---
{{- end }}
