{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "celine-services.fullname" . }}-data
  labels:
    {{- include "celine-services.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.qdrant.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "celine-services.fullname" . }}-qdrant
  labels:
    {{- include "celine-services.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.qdrant.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.qdrant.size }}
{{- end }}
