secure: false

realm: celine
domain: celine.local
issuer: celine-tls

realmAdmin:
  username: "celine-admin"
  email: "admin@celine.local"
  password: "celine-admin"

oauth2Proxy:
  clientID: oauth2_proxy
  # openssl rand -hex 16
  clientSecret: 88a52beb361e342e19c0fe82cbda7acb
  cookieSecret: 411e509ecac4adca7be836fd8d337310
  clientCLISecret: 2e19c0fe82cbda7acbe509e88a52beb3

dashboard_items:
  - name: Webapp
    host: webapp
  - name: AI Assistant
    host: assistant
  - name: BI Dashboards (Superset)
    host: superset
  - name: Data Lineage (Marquez)
    host: marquez
  - name: Security (Keycloak)
    host: keycloak
  - name: Data Pipelines (Prefect)
    host: prefect
