apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-ingestor.fullname" . }}
  labels:
    {{- include "mqtt-ingestor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mqtt-ingestor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mqtt-ingestor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "mqtt-ingestor.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:

            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret | default .Values.db.name }}
                  key: {{ .Values.db.key }}

            # --- MQTT credentials and host ---
            - name: MQTT_BROKER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.existingSecret | default (printf "%s-mqtt" (include "mqtt-ingestor.fullname" .)) }}
                  key: MQTT_BROKER
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.existingSecret | default (printf "%s-mqtt" (include "mqtt-ingestor.fullname" .)) }}
                  key: MQTT_USER
            - name: MQTT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.existingSecret | default (printf "%s-mqtt" (include "mqtt-ingestor.fullname" .)) }}
                  key: MQTT_PASS                  
          envFrom:
            - configMapRef:
                name: {{ include "mqtt-ingestor.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
