{{- if and .Values.db.create (not .Values.db.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}
  labels:
    {{- include "mqtt-ingestor.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.db.data }}
{{- range $k, $v := .Values.db.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- else }}
  {{ .Values.db.key }}: {{ .Values.db.value | quote }}
{{- end }}
{{- end }}