{{- if and .Values.mqtt.create (not .Values.mqtt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mqtt.name | default (printf "%s-mqtt" (include "mqtt-ingestor.fullname" .)) }}
  labels:
    {{- include "mqtt-ingestor.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.mqtt.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}