apiVersion: v2
name: celine-dataset-api
description: CELINE Dataset API service
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: celine-services
    version: "0.1.0"
    repository: file://../celine-services
