apiVersion: v2
name: celine-policies
description: CELINE Policy / MQTT auth service (celine.mqtt_auth.main:create_app)
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: celine-services
    version: "0.1.0"
    repository: file://../celine-services
