apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  labels:
    app: oauth2-proxy
type: Opaque
stringData:
  client-id: {{ .Values.oauth2Proxy.clientID }}
  client-secret: {{ .Values.oauth2Proxy.clientSecret }}
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | quote }}
  
