{{- if .Values.search.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "marquez.fullname" . }}-opensearch
spec:
  serviceName: {{ include "marquez.fullname" . }}-opensearch
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marquez-opensearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marquez-opensearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: opensearch
          image: {{ .Values.image.opensearch }}
          ports:
            - containerPort: 9200
          env:
            - name: cluster.name
              value: opensearch-cluster
            - name: node.name
              value: opensearch
            - name: discovery.seed_hosts
              value: opensearch
            - name: cluster.initial_cluster_manager_nodes
              value: opensearch
            - name: bootstrap.memory_lock
              value: "true"
            - name: plugins.security.ssl.http.enabled
              value: "false"
            - name: "OPENSEARCH_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
