---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marquez.fullname" . }}-web
spec:
  selector:
    app.kubernetes.io/name: marquez-web
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: 5002
