{{- $host := .Values.host }}
{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-account-{{ .username }}
  labels:
    app.kubernetes.io/name: mqtt-accounts
type: Opaque
stringData:
  MQTT_BROKER: "{{ $host }}"
  MQTT_USER: "{{ .username }}"
  MQTT_PASS: "{{ .password }}"
---
{{- end }}