apiVersion: v2
name: celine-ai-assistant
description: CELINE AI Assistant service
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: celine-services
    version: "0.1.0"
    repository: file://../celine-services
